apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aatiwarishubaks-fbb7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aatiwarishubaks-fbb7"
  template:
    metadata:
      labels:
        app: "aatiwarishubaks-fbb7"
    spec:
      containers:
        - name: "aatiwarishubaks-fbb7"
          image: "aaaatiwarishubregistry.azurecr.io/aatiwarishubaksfbb7"
          ports:
          - containerPort: 80