apiVersion: v1
kind: Service
metadata:
    name: "aatiwarishubaks-dc1b"
    labels:
        app: "aatiwarishubaks-dc1b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aatiwarishubaks-dc1b"