on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{secrets.acr_aaaatiwarishubregistry_username}}
        password: ${{secrets.acr_aaaatiwarishubregistry_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/go/plain/container/Application" -f  "go/plain/container/Application/Dockerfile" -t aaaatiwarishubregistry.azurecr.io/aatiwarishubaksdc1b:${{ github.sha }}
        docker push aaaatiwarishubregistry.azurecr.io/aatiwarishubaksdc1b:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_aatiwarishubaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aatiwarishubaksdc1b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aatiwarishubaksdc1b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aatiwarishubaksdc1b
        container-registry-url: aaaatiwarishubregistry.azurecr.io
        container-registry-username: ${{secrets.acr_aaaatiwarishubregistry_username}}
        container-registry-password: ${{secrets.acr_aaaatiwarishubregistry_password}}
        secret-name: aatiwarishubdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aatiwarishubaksdc1b
        manifests: |
          go/plain/container/Application/manifests/deployment-dc1b.yml
          go/plain/container/Application/manifests/service-dc1b.yml
        images: |
          aaaatiwarishubregistry.azurecr.io/aatiwarishubaksdc1b:${{ github.sha }}
        imagepullsecrets: |
          aatiwarishubdockerauth